name: gitklient
version: '0.1'
grade: stable
adopt-info: gitklient

confinement: strict
base: core18

apps:
  gitklient:
    common-id: org.kde.gitklient.desktop
    command: gitklient
    extensions:
      - kde-neon
    plugs:
      - home

slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.gitklient.desktop
    bus: session

parts:
  gitklient:
    parse-info:
      - usr/share/metainfo/org.kde.gitklient.appdata.xml
    plugin: cmake
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    build-packages:
      - kdoctools-dev
    source: https://invent.kde.org/sdk/gitklient/-/archive/master/gitklient-master.tar.gz
    configflags:
      - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
